version: '3.4'

services:
  shoppy_api:
    container_name: shoppy_api
    image: ${DOCKER_REGISTRY-}shoppywebapi
    build:
      context: .
      dockerfile: src/WebApi/ServiceHost/Dockerfile
  
  shoppy_db:
    container_name: shoppy_db
    image: mongo
